name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.push-image.outputs.image }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # GHCR requires lowercase.
      - id: repolower
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ steps.repolower.outputs.lowercase }}:${{ github.sha }}, ghcr.io/${{ steps.repolower.outputs.lowercase }}:latest

  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-image
  #   steps:
  #   - uses: imranismail/setup-kustomize@v1

  #   - name: Update env/dev image with Kustomize
  #     run: |
  #       git config --global user.name "Deploy Bot"
  #       git config --global user.email "no-reply@akuity.io"
  #       git clone https://bot:${{ secrets.DEPLOY_PAT }}@github.com/${{ github.repository_owner }}/demo-app-deploy.git
  #       cd demo-app-deploy/env/dev
  #       kustomize edit set image ghcr.io/${{ github.repository_owner }}/demo-app:${{ github.sha }}
  #       git commit -a -m "chore(dev): deploy demo-app:${{ github.sha }}"
  #       git notes append -m "image: ghcr.io/${{ github.repository_owner }}/demo-app:${{ github.sha }}"
  #       git push origin "refs/notes/*" --force && git push --force
